name: Docker Build and Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build Docker Image and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker-compose build

      - name: Push Docker Image
        run: docker-compose push

      - name: Run Tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Linter (Flake8)
        run: docker-compose run --rm app sh -c "flake8"
